USE [C:\PROJECTS\ASUSGIGAINSP\LOCALDB\ASUSGIGAINSP.MDF]
GO

/****** Object:  Table [dbo].[M_SERIAL_STATUS]    Script Date: 2020/06/23 9:50:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[M_SERIAL_STATUS](
	[SERIAL_STATUS_ID] [nvarchar](4) NOT NULL,
	[SERIAL_STATUS_NAME] [nvarchar](max) NULL,
	[DEL_FLG] [nchar](1) NULL,
	[INSERT_DATE] [datetime] NULL,
	[INSERT_ID] [nvarchar](max) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_ID] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[SERIAL_STATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

