USE [C:\PROJECTS\ASUSGIGAINSP\LOCALDB\ASUSGIGAINSP.MDF]
GO

/****** Object:  Table [dbo].[T_SERIAL_STATUS_HYSTORY]    Script Date: 2020/06/23 9:52:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_SERIAL_STATUS_HYSTORY](
	[SERIAL_ID] [bigint] NOT NULL,
	[SERIAL_NUMBER] [nvarchar](15) NULL,
	[LINE_ID] [nvarchar](50) NOT NULL,
	[SO_NO] [nvarchar](50) NULL,
	[STATUS] [nvarchar](4) NOT NULL,
	[INSERT_DATE] [datetime] NULL,
	[INSERT_UID] [nvarchar](10) NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[UPDATE_UID] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[SERIAL_ID] ASC,
	[LINE_ID] ASC,
	[UPDATE_DATE] ASC,
	[STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

