CREATE TABLE [dbo].[T_SERIAL_LIST] (
    [ID]                  BIGINT         NOT NULL,
    [SERIAL_NUMBER]       NVARCHAR (15)  NULL,
    [ASUS_PART_NO]        NVARCHAR (MAX) NULL,
    [DESCRIPTION]         NVARCHAR (MAX) NULL,
    [SPECIFICATION]       NVARCHAR (MAX) NULL,
    [PALLET]              NVARCHAR (MAX) NULL,
    [CARTON]              NVARCHAR (MAX) NULL,
    [MAC_1]               NVARCHAR (12)  NULL,
    [MAC_2]               NVARCHAR (12)  NULL,
    [MODEL_NAME]          NVARCHAR (MAX) NULL,
    [CUSTOMER_MODEL_NAME] NVARCHAR (MAX) NULL,
    [NW]                  NVARCHAR (MAX) NULL,
    [GW]                  NVARCHAR (MAX) NULL,
    [EAN_CODE]            NVARCHAR (MAX) NULL,
    [UPC_CODE]            NVARCHAR (MAX) NULL,
    [BIOS]                NVARCHAR (MAX) NULL,
    [IMEI]                NVARCHAR (MAX) NULL,
    [IMEI2]               NVARCHAR (MAX) NULL,
    [LOCK_CODE]           NVARCHAR (MAX) NULL,
    [SHIPPING_DATE]       DATETIME NULL,
    [SO]                  NVARCHAR (MAX) NULL,
    [SO_LINE]             NVARCHAR (MAX) NULL,
    [OSVER]               NVARCHAR (MAX) NULL,
    [MODEMVER]            NVARCHAR (MAX) NULL,
    [FWVER]               NVARCHAR (MAX) NULL,
    [GPSVER]              NVARCHAR (MAX) NULL,
    [MAPVER]              NVARCHAR (MAX) NULL,
    [MB_MAC]              NVARCHAR (MAX) NULL,
    [BCAS_CARD]           NVARCHAR (MAX) NULL,
    [H3GBARCODE]          NVARCHAR (MAX) NULL,
    [COM_SN1]             NVARCHAR (MAX) NULL,
    [COM_SN2]             NVARCHAR (MAX) NULL,
    [COM_SN3]             NVARCHAR (MAX) NULL,
    [COM_MAC1]            NVARCHAR (MAX) NULL,
    [COM_MAC2]            NVARCHAR (MAX) NULL,
    [COM_MAC3]            NVARCHAR (MAX) NULL,
    [INSERT_DATE]         DATETIME       NULL,
    [INSERT_ID]           NVARCHAR (10)  NULL,
    [UPDATE_DATE]         DATETIME       NULL,
    [UPDATE_ID]           NVARCHAR (10)  NULL,
    CONSTRAINT [PK_T_SERIAL_LIST] PRIMARY KEY CLUSTERED ([ID] ASC)
);

