USE [C:\PROJECTS\ASUSGIGAINSP\LOCALDB\ASUSGIGAINSP.MDF]
GO

/****** Object:  Table [dbo].[T_SO_LIST]    Script Date: 2020/06/23 9:52:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_SO_LIST](
	[SO_ID] [nvarchar](50) NOT NULL,
	[SO_NO] [nvarchar](50) NULL,
	[n90N] [nvarchar](50) NULL,
	[MODEL_NAME] [nvarchar](50) NULL,
	[SHIPPING_QUANTITY] [int] NOT NULL,
	[EST_ARRIVAL_DATE] [date] NULL,
	[PREF_REPORTING_DATE] [date] NULL,
	[SI_TEK_EST_ARRIVAL_DATE] [date] NULL,
	[DELIVERY_LOCATION] [nvarchar](50) NULL,
	[N01_NO] [nvarchar](50) NULL,
	[DEL_FLG] [nchar](1) NOT NULL,
	[INSERT_DATE] [datetime] NULL,
	[INSERT_UID] [nvarchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_UID] [nvarchar](10) NULL,
 CONSTRAINT [PK_T_SO_LIST] PRIMARY KEY CLUSTERED 
(
	[SO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_SO_LIST] ADD  CONSTRAINT [DF_T_SO_LIST_SHIPPING_QUANTITY]  DEFAULT ((0)) FOR [SHIPPING_QUANTITY]
GO

ALTER TABLE [dbo].[T_SO_LIST] ADD  CONSTRAINT [DF_T_SO_LIST_DEL_FLG]  DEFAULT ('0') FOR [DEL_FLG]
GO

