USE [C:\PROJECTS\ASUSGIGAINSP\LOCALDB\ASUSGIGAINSP.MDF]
GO

/****** Object:  Table [dbo].[T_SO_STATUS]    Script Date: 2020/06/23 9:53:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_SO_STATUS](
	[SO_ID] [nvarchar](50) NOT NULL,
	[SO_NO] [nvarchar](50) NULL,
	[n90N] [nvarchar](50) NULL,
	[MODEL_NAME] [nvarchar](50) NULL,
	[SHIPPING_QUANTITY] [int] NOT NULL,
	[EST_ARRIVAL_DATE] [date] NULL,
	[PREF_REPORTING_DATE] [date] NULL,
	[SI_TEK_EST_ARRIVAL_DATE] [date] NULL,
	[DELIVERY_LOCATION] [nvarchar](50) NULL,
	[N01_NO] [nvarchar](50) NULL,
	[SO_STATUS_ID] [nvarchar](4) NULL,
	[COMPLETE_WORK_UNIT] [int] NOT NULL,
	[DOA_UNIT] [int] NOT NULL,
	[ST_CHANGE_DATE] [datetime] NULL,
	[DEL_FLG] [nchar](1) NOT NULL,
	[INSERT_DATE] [datetime] NULL,
	[INSERT_UID] [nvarchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_UID] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[SO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_SO_STATUS] ADD  CONSTRAINT [DF_T_SO_STATUS_SHIPPING_QUANTITY]  DEFAULT ((0)) FOR [SHIPPING_QUANTITY]
GO

ALTER TABLE [dbo].[T_SO_STATUS] ADD  CONSTRAINT [DF_T_SO_STATUS_COMPLETE_WORK_UNIT]  DEFAULT ((0)) FOR [COMPLETE_WORK_UNIT]
GO

ALTER TABLE [dbo].[T_SO_STATUS] ADD  CONSTRAINT [DF_T_SO_STATUS_DOA_UNIT]  DEFAULT ((0)) FOR [DOA_UNIT]
GO

ALTER TABLE [dbo].[T_SO_STATUS] ADD  CONSTRAINT [DF_T_SO_STATUS_DEL_FLG]  DEFAULT ('0') FOR [DEL_FLG]
GO

