USE [C:\PROJECTS\ASUSGIGAINSP\LOCALDB\ASUSGIGAINSP.MDF]
GO

/****** Object:  Table [dbo].[T_SO_STATUS_HYSTORY]    Script Date: 2020/06/23 9:53:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_SO_STATUS_HYSTORY](
	[SO_ID] [nvarchar](50) NOT NULL,
	[SEQ] [int] NOT NULL,
	[SO_NO] [nvarchar](50) NULL,
	[BEFORE_STATUS] [nvarchar](4) NULL,
	[NOW_STATUS] [nvarchar](4) NULL,
	[INSERT_DATE] [datetime] NULL,
	[INSERT_UID] [nvarchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_UID] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[SO_ID] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

